services:
  bta-backend:
    image: riddhich/brain-tumor-analysis-backend:latest
    container_name: brain-tumor-analysis-backend
    # Keep stdin_open because we don't want this container to exit immediately which it
    # otherwise would have because there's no foreground processes
    stdin_open: true
    ports:
      - "3500:3500"
    # Using Docker volume for persisting logs
    # ./logs refers to the path on the host machine
    # and we're linking it to logs folder on the container machine where Morgan logger logs its output
    volumes:
      - ./logs:/brain_tumor_analysis/logs/
  bta-frontend:
    image: riddhich/brain-tumor-analysis-frontend:latest
    container_name: brain-tumor-analysis-frontend
    # Keep stdin_open because we don't want this container to exit immediately which it
    # otherwise would have because there's no foreground processes
    stdin_open: true
    ports:
      - "3000:3000"
